### ISSUE TITLE
defmt not working as expected

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/esp-println#52]
I've generated a template project (`cargo generate esp-rs/esp-template --name test -d mcu=esp32c3 -d advanced=false`), updated the `esp-println` feature to `esp-println = { git = "https://github.com/esp-rs/esp-println", features = ["esp32c3", "defmt"]  }`, included the `defmt` crate and tried several things:
- If we use `espflash v2.1.0` which does not have `defmt` support:
  - `esp_println::println!("Hello world!")` prints the message
  - Using any `defmt` macro results in a linker error, which I guess is expected
- If we use `espflash v2.1.1-dev` (`main` branch) with `defmt` feature
  - `defmt::println!("Hello world!")` results in a linker error
  - `defmt::debug!("Hello world!")` builds but does not print the message, same for `defmt::info` and `defmt::warn`
  - `defmt::error!` results in a linker error
   - `esp_println::println` prints the message fine
- If we use `espflash v2.1.1-dev` (`main` branch) with `defmt` feature
  - `defmt::println!("Hello world!")` results in a linker error
  - `defmt::debug!("Hello world!")` builds but does not print the message, same for `defmt::info` and `defmt::warn`
  - `defmt::error!` results in a linker error
  - `esp_println::println` prints the message fine
Using the `defmt-raw` instead of the `defmt` feature in `esp-println` results in similar outputs.

cc @bugadani

**Comment by SergioGasquez** [comment]
> you need to set DEFMT_LOG to some level to print messages above that level

Did some quick testing, trying to print a defmt::info! with `DEFMT_LOG=warn` does not print the message, with `DEFMT_LOG=info`results in linker script error

**Comment by bugadani** [comment]
![image](https://github.com/esp-rs/esp-println/assets/977627/576d49ba-6e97-41ca-9fa6-c27011e307fe)

works as expected. you'll need to add to your `.cargo/config.toml` this line:

```
[target.xtensa-esp32s3-none-elf]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-Trom_functions.x",
  "-C", "link-arg=-Tdefmt.x", <--- this
]
```

**Comment by SergioGasquez** [comment]
Still not working for me, I also tried with S3:
1. `cargo generate esp-rs/esp-template --name=defmt -d mcu=esp32s3 -d advanced=false`
2. Modified .cargo/config.toml:
```tomlç[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[build]
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
  "-C",
  "link-arg=-nostartfiles",
  "-C",
  "link-arg=-Tdefmt.x",
  "-C",
  "link-arg=-Trom_functions.x",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
```
3. Modified Cargo.toml, added: 
```
esp-println = { git = "https://github.com/esp-rs/esp-println", features = [
    "esp32s3",
    "defmt-raw",
] }
defmt = "0.3.5"
```
4. Removed `esp_println::prinln!` calls in `main.rs` and added `defmt::info!("Hello world!");`
5. `DEFMT_LOG=info cargo r` results in linker error

**Comment by bugadani** [comment]
Please don't use `defmt-raw`. It's meant as an advanced feature for folks who _only_ use defmt and have the tools to read it. espflash users are supposed to use `defmt` instead.

> cannot open linker script file rom_functions.x

I can reproduce this error, but this is an esp-wifi file and is not necessary for defmt. Remove the 
```
  "-C",
  "link-arg=-Trom_functions.x",
```

part and the project compiles.

**Comment by SergioGasquez** [comment]
> Please don't use defmt-raw. It's meant as an advanced feature for folks who only use defmt and have the tools to read it. espflash users are supposed to use defmt instead.

Ups, that was a typo, let me try without rom functions

**Comment by SergioGasquez** [comment]
Still getting linker error or nothing printed. 
- main.rs:
```rust
#![no_std]
#![no_main]

use esp_backtrace as _;
use hal::{clock::ClockControl, peripherals::Peripherals, prelude::*, Delay};

#[entry]
fn main() -> ! {
    let peripherals = Peripherals::take();
    let system = peripherals.SYSTEM.split();
    let clocks = ClockControl::max(system.clock_control).freeze();
    let mut delay = Delay::new(&clocks);

    // println!("Hello world!");
    defmt::warn!("Hello world!");
    loop {
        defmt::info!("Hello world!");

        // println!("Loop...");
        delay.delay_ms(500u32);
    }
}
```
- Cargo.toml
```toml
[package]
name    = "defmt"
version = "0.1.0"
authors = ["Sergio Gasquez <sergio.gasquez@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal = { package = "esp32s3-hal", version = "0.12.0" }
esp-backtrace = { version = "0.8.0", features = [
    "esp32s3",
    "panic-handler",
    "exception-handler",
    "print-uart",
] }
esp-println = { git = "https://github.com/esp-rs/esp-println", features = [
    "esp32s3",
    "defmt",
] }
defmt = "0.3.5"
```
- .cargo/config.toml
```toml
[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[build]
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",
  "-C",
  "link-arg=-nostartfiles",
  "-C",
  "link-arg=-Tdefmt.x",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
```
